---
title: "data-jam"
output: html_document
---

using csv files

### Change this to your path

```{r}
setwd("~/datajams/data-jam-august-2016/")
```

### Loading in libraries

```{r}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)

counties <- map_data("county")
tx <- subset(counties, region=="texas")
```

I loaded all the data but I guess you only need the primary results

```{r}
dict <- read.csv("csv/county_facts_dictionary.csv",header=T,as.is=T)
fact <- read.csv("csv/county_facts.csv",header=T,as.is=T)
res <- read.csv("csv/primary_results.csv",header=T,as.is=T)
```

### subset to Texas

```{r}
dtx <- res[res$state=="Texas",]
tx.facts <- fact[fact$state_abbreviation=="TX",]
```

Make lowercase for merging

```{r}
dtx$county <- tolower(dtx$county)
```

### Find the winner for every county

```{r}
dtx$county.win <- ""
for (i in 1:nrow(dtx)) {
  tmp <- dtx[dtx$county == dtx$county[i] & dtx$party == dtx$party[i],]
  winner <- tmp[which(tmp$votes==max(tmp$votes))[1],"candidate"] # in case of tie, choose first name for simplicity
  dtx$county.win[i] <- winner
}
```

### Merge by county name

```{r}
m <- merge(dtx, tx, by.x="county", by.y="subregion")
```

### Make the plot

```{r}
ggplot() + geom_polygon(data=m, aes(x=long, y = lat, group = group, fill=county.win)) + 
  coord_fixed(1.3) + facet_wrap( ~ party) + theme(strip.text = element_text(size = 12)) + 
  scale_fill_manual(
    guide = guide_legend(title = "Winning Candidate"),
    values=c("Ben Carson"="turquoise3",
             "Bernie Sanders"="goldenrod",
             "Donald Trump"="slateblue1",
             "Hillary Clinton"="royalblue1",
             "Ted Cruz"="indianred3")) + 
  ggtitle("Who got the most votes in Texas?")
```
